// misc/config_tools/configurator/packages/configurator/src/components/common/Footer.vue
<template>
  <div class="pt-3">
    <p class="text-center text-secondary">
      © Copyright Project ACRN™, a Series of LF Projects, LLC.
      <text v-if="version" @click="home">- Version {{ version }}</text>
    </p>
  </div>
</template>

<script>
import {getVersion} from "@tauri-apps/api/app";


export default {
  name: "Footer",
  data: () => {
    return {
      version: ''
    }
  },
  mounted() {
	this.version = packageVersion
  },
  methods: {
    home() {
      this.$router.push('/')
    },
  }
}
</script>

<style scoped>

</style>

// misc/config_tools/configurator/src/components/Footer/footer.jsx
import {Component} from "react";
import {getVersion} from "@tauri-apps/api/app";


export default class Footer extends Component {
    constructor(props) {
        super(props);
        this.state = {
            version: "0.1.0"
        }
    }

    componentDidMount = () => {
        getVersion().then((version) => {
            this.setState({version: version})
        })
    }

    render = () => {
        return <div className="pt-3">
            <p className="text-center text-secondary">© Copyright Project ACRN™, a Series of LF Projects, LLC.
                - Version {this.state.version}</p>
        </div>
    }
}
